### ISSUE TITLE
game crashes with 1.18.2

### ISSUE THREAD

**Issue by wojciechsacewicz** [ModsByLeo/DontDropIt#29] opened 2022-03-27 22:01 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Version information

1.18.2 fabric

### Expected Behavior

open the game and play

### Actual Behavior

game crashes in 1.18.2

### Reproduction Steps

1.18.2 fabric > put mod in folder > open game > crash on startup

### Java version

69

### Additional information

pls fix

**Comment by Leo40Git** [comment] 2022-03-28 05:37
Please add a crash log... and fill the template with actual information (I assume you're using Java 17).

**Comment by olivergame** [comment] 2022-04-07 18:25
Version information

1.18.2 fabric
Expected Behavior

open the game and play
Actual Behavior

game crashes in 1.18.2
Reproduction Steps

1.18.2 fabric > put mod in folder > open game > crash on startup

same problem

[20:23:34] [main/INFO]: Loading Minecraft 1.18.2 with Fabric Loader 0.13.3
[20:23:35] [main/INFO]: Loading 201 mods:
	- advanced_runtime_resource_pack 0.5.5 via enhancedblockentities
	- amecsapi 1.3.3+mc1.18-pre1 via dontdropit
	- animatica 0.4+1.18
	- architectury 4.1.39
	- armorhud 1.18-1.2.1
	- autoconfig1u 3.2.2 via capes
	- autofish 0.9.4
	- autoswitch 4.0.3
	- autoswitch-api 1.1.0 via autoswitch
	- betterbeds 1.2.0
	- blue_endless_jankson 1.2.1 via jankson
	- blur 2.4.1
	- bookshelf 13.0.8
	- c2me 0.2.0+alpha.7.0
	- caffeineconfig 1.1.0 via sodium-extra
	- capes 1.2.2+1.18
	- cardinal-components-base 4.1.4 via pickupnotifier
	- cardinal-components-entity 4.1.4 via pickupnotifier
	- cem 0.7.1
	- chesttracker 1.1.13
	- citresewn 1.0.1+1.18.2
	- citresewn-defaults 1.0.1+1.18.2 via citresewn
	- cleardespawn 21w40a-1.1.3
	- clickthrough 1.18.2-fabric0.47.10-0.4
	- cloth-api 3.2.64
	- cloth-basic-math 0.6.0 via cloth-api
	- cloth-client-events-v0 3.2.64 via cloth-api
	- cloth-common-events-v1 3.2.64 via cloth-api
	- cloth-config 6.2.57 via dynamicsoundfilters
	- cloth-datagen-api-v1 3.2.64 via cloth-api
	- cloth-scissors-api-v1 3.2.64 via cloth-api
	- cloth-utils-v1 3.2.64 via cloth-api
	- com_electronwill_night-config_core 3.6.3 via forgeconfigapiport
	- com_electronwill_night-config_toml 3.6.3 via forgeconfigapiport
	- com_github_llamalad7_mixinextras 0.0.6 via evergreenhud
	- com_github_luben_zstd-jni 1.5.2-2 via dashloader
	- com_ishland_c2me_libs_ 0.2.0+alpha.7.0 via c2me
	- com_velocitypowered_velocity-native 1.1.0-SNAPSHOT via krypton
	- commons-codec_commons-codec 1.10 via evergreenhud
	- commons-logging_commons-logging 1.2 via evergreenhud
	- completeconfig 1.0.0 via cem
	- continuity 1.1.0+1.18.2
	- crowdin-translate 1.4+1.18.2 via clickthrough
	- cullleaves 2.3.2
	- dark-loading-screen 1.6.11
	- dashloader 3.1.1+1.18
	- dcch 2.0+1.17
	- detailab 2.6.2+1.18-fabric
	- dev_isxander_settxi 2.1.0 via evergreenhud
	- dev_quantumfusion_dashloader_dashloader-core 1.4.0 via dashloader
	- dev_quantumfusion_hyphen 0.2.0 via dashloader
	- dontdropit 2.3.8+1.18
	- dsurround 0.0.4
	- dynamicsoundfilters 1.3.0+1.18.2
	- easiervillagertrading 1.18.2-fabric0.47.10-1.5.4
	- elementa 427 via evergreenhud
	- enchantment_lore 1.2.6-1
	- enchdesc 10.0.2
	- enhancedblockentities 0.6+1.18.2
	- entity_texture_features 2.6.0
	- evergreenhud 2.0.0-alpha.6
	- extrasounds 2.2.1+1.18.2
	- fabric 0.48.0+1.18.2
	- fabric-api-lookup-api-v1 1.5.7+d7c144a860 via fabric
	- fabric-biome-api-v1 8.0.3+801ec85b60 via fabric
	- fabric-blockrenderlayer-v1 1.1.12+3ac43d9560 via fabric
	- fabric-commands-v0 0.2.8+b4f4f6cd60 via fabric
	- fabric-containers-v0 0.1.21+d7c144a860 via fabric
	- fabric-content-registries-v0 3.0.2+d82b939260 via fabric
	- fabric-crash-report-info-v1 0.1.11+3ac43d9560 via fabric
	- fabric-dimensions-v1 2.1.17+2540745460 via fabric
	- fabric-entity-events-v1 1.4.8+d7c144a860 via fabric
	- fabric-events-interaction-v0 0.4.19+d7c144a860 via fabric
	- fabric-events-lifecycle-v0 0.2.13+d7c144a860 via fabric
	- fabric-game-rule-api-v1 1.0.13+d7c144a860 via fabric
	- fabric-item-api-v1 1.3.3+691a79b560 via fabric
	- fabric-item-groups-v0 0.3.10+3ac43d9560 via fabric
	- fabric-key-binding-api-v1 1.0.12+54e5b2ec60 via fabric
	- fabric-keybindings-v0 0.2.10+b4f4f6cd60 via fabric
	- fabric-language-kotlin 1.7.2+kotlin.1.6.20
	- fabric-loot-tables-v1 1.0.11+d7c144a860 via fabric
	- fabric-mining-level-api-v1 2.0.4+d1027f7d60 via fabric
	- fabric-models-v0 0.3.6+d7c144a860 via fabric
	- fabric-networking-api-v1 1.0.21+d882b91560 via fabric
	- fabric-networking-v0 0.3.8+b4f4f6cd60 via fabric
	- fabric-object-builder-api-v1 2.0.3+40c91ec860 via fabric
	- fabric-particles-v1 0.2.12+526dc1ac60 via fabric
	- fabric-registry-sync-v0 0.9.8+0d9ab37260 via fabric
	- fabric-renderer-api-v1 0.4.13+d882b91560 via fabric
	- fabric-renderer-indigo 0.4.17+d8c7b9ae60 via fabric
	- fabric-renderer-registries-v1 3.2.11+b4f4f6cd60 via fabric
	- fabric-rendering-data-attachment-v1 0.3.7+d7c144a860 via fabric
	- fabric-rendering-fluids-v1 2.0.2+54e5b2ec60 via fabric
	- fabric-rendering-v0 1.1.13+b4f4f6cd60 via fabric
	- fabric-rendering-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- fabric-resource-conditions-api-v1 2.0.2+d1027f7d60 via fabric
	- fabric-screen-api-v1 1.0.10+d882b91560 via fabric
	- fabric-screen-handler-api-v1 1.1.14+40c91ec860 via fabric
	- fabric-textures-v0 1.0.12+3ac43d9560 via fabric
	- fabric-transfer-api-v1 1.5.14+cca23f9360 via fabric
	- fabric-transitive-access-wideners-v1 1.0.0+40c91ec860 via fabric
	- fabricloader 0.13.3
	- fabrilousupdater 2.6+1.18.2
	- fallingleaves 1.10.0+1.18.2
	- ferritecore 4.2.0
	- forgeconfigapiport 3.2.0
	- friendlyfarmer 1.1.0
	- gammautils 1.5.6
	- gbfabrictools 1.3.4+1.17 via cleardespawn
	- head-down-display 0.2.0
	- indium 1.0.2+mc1.18.2
	- inspecio 1.3.0+1.18
	- inventoryprofilesnext 1.3.5
	- io_ktor_ktor-client-apache-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-client-content-negotiation-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-client-core-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-events-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-http-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-io-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-kotlinx-json-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-serialization-kotlinx-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-utils-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-websocket-serialization-jvm 2.0.0-beta-1 via evergreenhud
	- io_ktor_ktor-websockets-jvm 2.0.0-beta-1 via evergreenhud
	- iris 1.2.2-build.32
	- jankson 4.0.0+j1.2.0 via libgui
	- java 17
	- kbootstrap 0.1.5 via head-down-display
	- kirin 1.10.0 via presencefootsteps
	- krypton 0.1.9
	- lambdabettergrass 1.2.3+1.18
	- lazydfu 0.1.2
	- libgui 5.3.1+1.18 via chesttracker
	- libninepatch 1.1.0 via libgui
	- lightlevel 3.0.0
	- lightoverlay 6.0.5
	- litematica 0.11.1
	- malilib 0.12.1
	- midnightlib 0.4.0 via puddles
	- minecraft 1.18.2
	- modmanager 1.2.3+1.18
	- modmenu 3.1.0
	- org_aeonbits_owner_owner 1.0.12 via autoswitch
	- org_anarres_jcpp 1.4.14 via iris
	- org_apache_httpcomponents_httpasyncclient 4.1.4 via evergreenhud
	- org_apache_httpcomponents_httpclient 4.5.6 via evergreenhud
	- org_apache_httpcomponents_httpcore 4.4.14 via evergreenhud
	- org_apache_httpcomponents_httpcore-nio 4.4.14 via evergreenhud
	- org_bundleproject_libversion 0.0.3 via evergreenhud
	- org_commonmark_commonmark 0.17.1 via evergreenhud
	- org_commonmark_commonmark-ext-gfm-strikethrough 0.17.1 via evergreenhud
	- org_commonmark_commonmark-ext-ins 0.17.1 via evergreenhud
	- org_dom4j_dom4j 2.1.1 via evergreenhud
	- org_jetbrains_kotlin_kotlin-reflect 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk7 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlin_kotlin-stdlib-jdk8 1.6.20 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-coroutines-jdk8 1.6.0 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-core-jvm 1.3.2 via fabric-language-kotlin
	- org_jetbrains_kotlinx_kotlinx-serialization-json-jvm 1.3.2 via fabric-language-kotlin
	- org_joml_joml 1.10.2 via sodium
	- org_openjdk_nashorn_nashorn-core 15.3 via dsurround
	- pickupnotifier 3.2.0
	- pinglist 1.3.3
	- presencefootsteps 1.5.0
	- puddles 1.2.1
	- puzzleslib 3.3.1
	- quilt_base 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-api-base
	- quilt_client_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_command 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-command-api-v1
	- quilt_lifecycle_events 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-lifecycle-events-v1
	- quilt_resource_loader 1.0.0+1.18.2-SNAPSHOT via quilted-fabric-resource-loader-v0
	- quilt_tags 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilt_tooltip 1.0.0+1.18.2-SNAPSHOT via fabric-rendering-v1
	- quilted-fabric-api-base 1.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-command-api-v1 2.0.0+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-lifecycle-events-v1 2.0.1+1.18.2-SNAPSHOT via inspecio
	- quilted-fabric-resource-loader-v0 1.0.0+1.18.2-SNAPSHOT via inspecio
	- reeses-sodium-options 1.4.2
	- satin 1.7.0 via blur
	- seamless_loading_screen 1.4.0+1.18.2
	- silence 1.18.2-fabric0.47.10-1.0.1
	- skinlayers 1.4.2-mc1.18.2
	- smoothboot 1.18.2-1.7.0
	- sodium 0.4.1+build.15
	- sodium-extra 0.4.3
	- soundcategories 1.2.1+1.18 via extrasounds
	- spruceui 3.3.3+1.18 via lambdabettergrass
	- starlight 1.0.2+fabric.89b8d9f
	- statuseffecttimer 1.1.0+1.18.1
	- stendhal 1.2.0-1.18
	- swordblocking 1.1.0
	- universalcraft 1.0.0 via evergreenhud
	- visualoverhaul 4.1.0
	- waveycapes 1.1.2
	- whereisit 1.14.10
	- xaerominimap 22.5.0
	- xaeroworldmap 1.20.6
[20:23:35] [main/WARN]: Mod `cleardespawn` (21w40a-1.1.3) does not respect SemVer - comparison support is limited.
[20:23:36] [main/INFO]: SpongePowered MIXIN Subsystem Version=0.8.5 Source=file:/C:/Users/olive/AppData/Roaming/.minecraft/libraries/net/fabricmc/sponge-mixin/0.11.2+mixin.0.8.5/sponge-mixin-0.11.2+mixin.0.8.5.jar Service=Knot/Fabric Env=CLIENT
[20:23:36] [main/INFO]: Compatibility level set to JAVA_16
[20:23:36] [main/INFO]: Compatibility level set to JAVA_17
[20:23:36] [main/INFO]: Configuration loaded successfully after 139.2685ms
[20:23:36] [main/INFO]: Successfully loaded configuration for C2ME
[20:23:36] [main/INFO]: Initializing C2ME Compatibility Module
[20:23:36] [main/INFO]: Preparing DashLoader 3.1.1+1.18.
[20:23:36] [main/WARN]: Disabled Optional Feature FAST_STATE_INIT from dashloader config. DashLoader
[20:23:36] [main/WARN]: Disabled Optional Feature CACHE_PARTICLE from dashloader config. DashLoader
[20:23:36] [main/WARN]: [Satin] Sodium is present, custom block renders may not work
[20:23:36] [main/INFO]: Loaded configuration file for Sodium: 29 options available, 5 override(s) found
[20:23:36] [main/INFO]: Loaded configuration file for Sodium Extra: 23 options available, 0 override(s) found
[20:23:37] [main/WARN]: Force-disabling mixin 'features.gui.fast_loading_screen.MixinLevelLoadingScreen' as rule 'mixin.features.gui.fast_loading_screen' (added by mods [seamless_loading_screen]) disables it and children
[20:23:37] [main/WARN]: Force-disabling mixin 'features.model.MixinMultipartBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[20:23:37] [main/WARN]: Force-disabling mixin 'features.model.MixinWeightedBakedModel' as rule 'mixin.features.model' (added by mods [dashloader]) disables it and children
[20:23:37] [main/WARN]: Force-disabling mixin 'features.sky.MixinWorldRenderer' as rule 'mixin.features.sky' (added by mods [iris]) disables it and children
[20:23:37] [main/WARN]: Force-disabling mixin 'features.texture_updates.MixinSpriteInterpolated' as rule 'mixin.features.texture_updates' (added by mods [dashloader]) disables it and children
[20:23:37] [main/INFO]: Adding mixins: [None]
[20:23:37] [main/WARN]: Error loading class: net/coderbot/iris/layer/IrisRenderLayerWrapper (java.lang.ClassNotFoundException: net/coderbot/iris/layer/IrisRenderLayerWrapper)
[20:23:37] [main/WARN]: @Mixin target net.coderbot.iris.layer.IrisRenderLayerWrapper was not found mixins.satin.client.json:iris.IrisRenderLayerWrapperMixin
[20:23:37] [main/INFO]: I used the json to destroy the json
[20:23:39] [main/INFO]: Trying to switch memory allocators to work around memory leaks present with Jemalloc 5.0.0 through 5.2.0 on Windows
[20:23:39] [DefaultDispatcher-worker-1/INFO]: Checking for mod updates...
[20:23:39] [main/INFO]: Initializing DashLoader 3.1.1+1.18.
[20:23:39] [main/INFO]: [56ms] Initialized api.
[20:23:39] [main/INFO]: Created DashLoader with KnotClassLoader.
[20:23:39] [main/INFO]: Initialized DashLoader
[20:23:39] [main/INFO]: Smooth Boot config initialized
[20:23:39] [DefaultDispatcher-worker-1/INFO]: No update for animatica found!
[20:23:39] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod architectury: No possible match found
[20:23:40] [main/WARN]: @Final field field_22786:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[20:23:40] [main/WARN]: @Final field field_33815:Ljava/util/List; in mixins.ipnext.json:MixinScreen should be final
[20:23:40] [main/INFO]: Bootstrap start
[20:23:40] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod armorhud: No possible match found
[20:23:40] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod autofish: No possible match found
[20:23:40] [main/WARN]: Method overwrite conflict for method_9522 in sodium.mixins.json:features.render_layer.leaves.MixinLeavesBlock, previously written by eu.midnightdust.cullleaves.mixin.MixinLeavesBlock. Skipping method.
[20:23:40] [DefaultDispatcher-worker-1/INFO]: No update for autoswitch found!
[20:23:41] [DefaultDispatcher-worker-1/INFO]: No update for betterbeds found!
[20:23:42] [DefaultDispatcher-worker-1/INFO]: No update for blur found!
[20:23:42] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod bookshelf: No possible match found
[20:23:42] [main/WARN]: @Inject(@At("INVOKE")) Shift.BY=3 on fabric-lifecycle-events-v1.mixins.json:client.WorldChunkMixin::handler$cfh000$onLoadBlockEntity exceeds the maximum allowed value: 0. Increase the value of maxShiftBy to suppress this warning.
[20:23:43] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod c2me: No possible match found
[20:23:43] [DefaultDispatcher-worker-1/INFO]: No update for capes found!
[20:23:43] [DefaultDispatcher-worker-1/INFO]: No update for cem found!
[20:23:43] [main/INFO]: Bootstrap in 3.8s
[20:23:44] [Render thread/WARN]: Method overwrite conflict for method_22920 in sodium.mixins.json:features.buffer_builder.intrinsics.MixinBufferBuilder, previously written by net.coderbot.iris.mixin.vertices.block_rendering.MixinBufferBuilder_SeparateAo. Skipping method.
[20:23:44] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod chesttracker: No possible match found
[20:23:44] [Render thread/INFO]: Environment: authHost='https://authserver.mojang.com', accountsHost='https://api.mojang.com', sessionHost='https://sessionserver.mojang.com', servicesHost='https://api.minecraftservices.com', name='PROD'
[20:23:44] [Render thread/INFO]: Setting user: Mayendra
[20:23:44] [DefaultDispatcher-worker-1/INFO]: No update for citresewn found!
[20:23:44] [Render thread/INFO]: [STDOUT]: Simple armor hud loaded!
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:pufferfish_bucket is now minecraft:bucket.
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:salmon_bucket is now minecraft:bucket.
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:cod_bucket is now minecraft:bucket.
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:tropical_fish_bucket is now minecraft:bucket.
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:axolotl_bucket is now minecraft:bucket.
[20:23:44] [Render thread/INFO]: Fixing MC-151457. Crafting remainder for minecraft:powder_snow_bucket is now minecraft:bucket.
[20:23:44] [DefaultDispatcher-worker-1/INFO]: No update for cleardespawn found!
[20:23:45] [Render thread/INFO]: Compression will use Java 11, encryption will use Java
[20:23:45] [Render thread/INFO]: Loading client config for pickupnotifier
[20:23:45] [Render thread/INFO]: [Stendhal] Initializing
[20:23:45] [Render thread/INFO]: AutoSwitch Loaded
[20:23:45] [DefaultDispatcher-worker-1/INFO]: No update for clickthrough found!
[20:23:45] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod cloth-api: No possible match found
[20:23:45] [DefaultDispatcher-worker-1/INFO]: No update for continuity found!
[20:23:46] [Render thread/INFO]: Loading 62 entities from Custom Entity Models 0.7.1
[20:23:46] [Render thread/INFO]: [citresewn] Registering CIT Conditions
[20:23:46] [Render thread/INFO]: [citresewn] Registering CIT Types
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:netherite_chestplate' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:diamond_helmet' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:turtle_helmet'!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:iron_helmet' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:chainmail_helmet' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:golden_helmet' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:leather_helmet' and 3 more items!
[20:23:46] [Render thread/INFO]: Successfully registered 'minecraft:elytra'!
[20:23:46] [Render thread/INFO]: Initializing...
[20:23:46] [Render thread/INFO]: Initialization complete
[20:23:46] [Render thread/INFO]: Loaded config file.
[20:23:46] [Render thread/INFO]: Saved config file.
[20:23:46] [Render thread/INFO]: [Entity Texture Features]: Loading! 1.18.x
[20:23:46] [Render thread/INFO]: Starting EvergreenHUD 2.0.0-alpha.6 for 1.18.2
[20:23:46] [DefaultDispatcher-worker-1/INFO]: No update for cullleaves found!
[20:23:47] [Render thread/INFO]: Registered 32 elements from source: core.
[20:23:47] [Render thread/INFO]: Finished loading EvergreenHUD. Took 211 ms.
[20:23:47] [Render thread/INFO]: [Indigo] Different rendering plugin detected; not applying Indigo.
[20:23:47] [Render thread/INFO]: Krypton is now accelerating your Minecraft client's networking stack ?
[20:23:47] [Render thread/INFO]: Note that Krypton is most effective on servers, not the client.
[20:23:47] [Render thread/INFO]: [LambdaBetterGrass] Initializing LambdaBetterGrass...
[20:23:47] [Render thread/INFO]: [LambdaBetterGrass] Configuration loaded.
[20:23:47] [DefaultDispatcher-worker-1/WARN]: Error while searching for fallback id for mod dark-loading-screen: No possible match found
[20:23:47] [DefaultDispatcher-worker-2/INFO]: Starting cleanup...
[20:23:47] [Render thread/ERROR]: Mod autoconfig1u provides a broken implementation of ModMenuApi
java.lang.NoClassDefFoundError: io/github/prospector/modmenu/api/ModMenuApi
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1012) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:223) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:174) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at java.lang.Class.forName0(Native Method) ~[?:?]
	at java.lang.Class.forName(Class.java:467) ~[?:?]
	at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.13.3.jar:?]
	at com.terraformersmc.modmenu.ModMenu.lambda$onInitializeClient$0(ModMenu.java:71) ~[modmenu-3.1.0.jar:?]
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?]
	at com.terraformersmc.modmenu.ModMenu.onInitializeClient(ModMenu.java:67) ~[modmenu-3.1.0.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:53) [fabric-loader-0.13.3.jar:?]
	at net.minecraft.class_310.<init>(class_310.java:452) [client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:197) [client-intermediary.jar:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?]
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?]
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?]
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77) [fabric-loader-0.13.3.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) [fabric-loader-0.13.3.jar:?]
Caused by: java.lang.ClassNotFoundException: io.github.prospector.modmenu.api.ModMenuApi
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:158) ~[fabric-loader-0.13.3.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
	... 27 more
[20:23:47] [DefaultDispatcher-worker-1/INFO]: No update for dashloader found!
[20:23:47] [Render thread/INFO]: Loading Xaero's Minimap - Stage 1/2
[20:23:47] [DefaultDispatcher-worker-1/INFO]: No update for dcch found!
[20:23:47] [Render thread/INFO]: Loading Xaero's World Map - Stage 1/2


hope this is usefull

**Comment by Leo40Git** [comment] 2022-04-07 18:28
This crash log does not contain anything to do with my mod.
1.18.2 is unsupported currently, and neither are versions I haven't released myself.
(an update will be released in ~3 weeks, I do not have computer access currently)

**Closed as completed by Leo40Git** 2022-04-07 18:28 UTC
Labels: bug
